# Generated by Django 4.2.7 on 2026-04-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('ssn', models.CharField(blank=True, max_length=20, verbose_name='SSN (US only)')),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('annual_income', models.CharField(blank=True, max_length=50)),
                ('source_of_funds', models.CharField(blank=True, max_length=200)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('residence_permit', 'Residence Permit')], max_length=50)),
                ('id_number', models.CharField(max_length=100)),
                ('id_expiry', models.DateField(blank=True, null=True)),
                ('id_front', models.ImageField(upload_to='kyc/ids/', verbose_name='ID Front')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='kyc/ids/', verbose_name='ID Back (if applicable)')),
                ('selfie', models.ImageField(upload_to='kyc/selfies/', verbose_name='Selfie with ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
